# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('quote', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_created', to='users.User')),
                ('users', models.ManyToManyField(related_name='quotes', to='users.User')),
            ],
        ),
    ]
